/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmbientBackground: typeof import('./components/common/AmbientBackground.vue')['default']
    AppDock: typeof import('./components/common/AppDock.vue')['default']
    AppShellLayout: typeof import('./layouts/AppShellLayout.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    CreateProjectDialog: typeof import('./components/dashboard/CreateProjectDialog.vue')['default']
    DashboardPage: typeof import('./pages/dashboard/DashboardPage.vue')['default']
    FileCard: typeof import('./components/chat/FileCard.vue')['default']
    FileUploadArea: typeof import('./components/chat/FileUploadArea.vue')['default']
    GlassPanel: typeof import('./components/common/GlassPanel.vue')['default']
    LLMSettings: typeof import('./components/settings/LLMSettings.vue')['default']
    MainLayout: typeof import('./layouts/MainLayout.vue')['default']
    ModeSwitchPill: typeof import('./components/common/ModeSwitchPill.vue')['default']
    ProjectCard: typeof import('./components/dashboard/ProjectCard.vue')['default']
    ProjectFilter: typeof import('./components/dashboard/ProjectFilter.vue')['default']
    ProjectGrid: typeof import('./components/dashboard/ProjectGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPage: typeof import('./pages/settings/SettingsPage.vue')['default']
    StorageSettings: typeof import('./components/settings/StorageSettings.vue')['default']
    ThemeSettings: typeof import('./components/settings/ThemeSettings.vue')['default']
    WorkspacePage: typeof import('./pages/workspace/WorkspacePage.vue')['default']
  }
}
