/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmbientBackground: typeof import('./components/common/AmbientBackground.vue')['default']
    AppDock: typeof import('./components/common/AppDock.vue')['default']
    AppShellLayout: typeof import('./layouts/AppShellLayout.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./components/chat/ChatMessage.vue')['default']
    ChatPanel: typeof import('./components/chat/ChatPanel.vue')['default']
    CreateProjectDialog: typeof import('./components/dashboard/CreateProjectDialog.vue')['default']
    DashboardPage: typeof import('./pages/dashboard/DashboardPage.vue')['default']
    ExportTaskPanel: typeof import('./components/preview/ExportTaskPanel.vue')['default']
    FileCard: typeof import('./components/chat/FileCard.vue')['default']
    FileUploadArea: typeof import('./components/chat/FileUploadArea.vue')['default']
    FullscreenPresenter: typeof import('./components/preview/FullscreenPresenter.vue')['default']
    GenerationProgressBanner: typeof import('./components/preview/GenerationProgressBanner.vue')['default']
    GlassPanel: typeof import('./components/common/GlassPanel.vue')['default']
    LinearProgressGlow: typeof import('./components/common/LinearProgressGlow.vue')['default']
    LLMSettings: typeof import('./components/settings/LLMSettings.vue')['default']
    MainLayout: typeof import('./layouts/MainLayout.vue')['default']
    ModeSwitchPill: typeof import('./components/common/ModeSwitchPill.vue')['default']
    OutlinePageItem: typeof import('./components/outline/OutlinePageItem.vue')['default']
    OutlinePanel: typeof import('./components/outline/OutlinePanel.vue')['default']
    PageGenerationProgressCard: typeof import('./components/chat/PageGenerationProgressCard.vue')['default']
    PageOptimizeChat: typeof import('./components/preview/PageOptimizeChat.vue')['default']
    PreviewPanel: typeof import('./components/preview/PreviewPanel.vue')['default']
    PreviewProjectChatEntry: typeof import('./components/preview/PreviewProjectChatEntry.vue')['default']
    ProjectCard: typeof import('./components/dashboard/ProjectCard.vue')['default']
    ProjectFilter: typeof import('./components/dashboard/ProjectFilter.vue')['default']
    ProjectGrid: typeof import('./components/dashboard/ProjectGrid.vue')['default']
    QuickActions: typeof import('./components/preview/QuickActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPage: typeof import('./pages/settings/SettingsPage.vue')['default']
    SlideControls: typeof import('./components/preview/SlideControls.vue')['default']
    SlideRenderer: typeof import('./components/preview/SlideRenderer.vue')['default']
    StorageSettings: typeof import('./components/settings/StorageSettings.vue')['default']
    ThemePresetPicker: typeof import('./components/preview/ThemePresetPicker.vue')['default']
    ThemeSettings: typeof import('./components/settings/ThemeSettings.vue')['default']
    ThinkingBubble: typeof import('./components/chat/ThinkingBubble.vue')['default']
    ThumbnailItem: typeof import('./components/preview/ThumbnailItem.vue')['default']
    ThumbnailNav: typeof import('./components/preview/ThumbnailNav.vue')['default']
    VersionHistoryDrawer: typeof import('./components/preview/VersionHistoryDrawer.vue')['default']
    WorkspacePage: typeof import('./pages/workspace/WorkspacePage.vue')['default']
  }
}
