from __future__ import annotations

from copy import deepcopy
from pathlib import Path
from typing import Any

from sqlalchemy import Select, select
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.config import Settings
from app.models import ChatMessage, PageVersion, Project, ProjectPage
from app.models.enums import PageStatus
from app.schemas.project import OutlinePageSchema


class PageServiceError(Exception):
    """Base exception for page generation persistence failures."""


class PageStorageError(PageServiceError):
    """Raised when page persistence to the database fails."""


class PageNotFoundError(PageServiceError):
    def __init__(self, project_id: str, page_number: int):
        super().__init__(f"Page {page_number} was not found in project '{project_id}'.")
        self.project_id = project_id
        self.page_number = page_number


class PageVersionNotFoundError(PageServiceError):
    def __init__(self, project_id: str, page_number: int, version: int):
        super().__init__(
            f"Version {version} for page {page_number} was not found in project '{project_id}'."
        )
        self.project_id = project_id
        self.page_number = page_number
        self.version = version


class PageMutationValidationError(PageServiceError):
    """Raised when a structural page mutation request is invalid."""


class InvalidPageOrderError(PageMutationValidationError):
    """Raised when the requested page order is not a valid permutation."""


class PreviewSlideWriteError(PageServiceError):
    """Raised when a preview slide file cannot be written safely."""


class PageService:
    _PAGE_NUMBER_OFFSET_BUFFER = 1000

    def __init__(self, session: AsyncSession, settings: Settings):
        self.session = session
        self.settings = settings

    async def upsert_generated_page(
        self,
        *,
        project_id: str,
        page_number: int,
        title: str | None,
        page_type: str | None,
        vue_code: str,
        status: PageStatus = PageStatus.GENERATED,
        change_description: str | None = "Generated by page generator.",
    ) -> ProjectPage:
        stmt: Select[tuple[ProjectPage]] = select(ProjectPage).where(
            ProjectPage.project_id == project_id,
            ProjectPage.page_number == page_number,
        )
        page = (await self.session.execute(stmt)).scalar_one_or_none()

        if page is None:
            page = ProjectPage(
                project_id=project_id,
                page_number=page_number,
                title=title,
                page_type=page_type,
                vue_code=vue_code,
                status=status,
                version=1,
            )
            self.session.add(page)
            self.session.add(
                PageVersion(
                    page=page,
                    version=1,
                    vue_code=vue_code,
                    change_description=change_description,
                )
            )
        else:
            page.title = title
            page.page_type = page_type
            self._append_version_snapshot(
                page,
                vue_code=vue_code,
                status=status,
                change_description=change_description,
            )

        try:
            await self.session.commit()
            await self.session.refresh(page)
        except SQLAlchemyError as exc:
            await self.session.rollback()
            raise PageStorageError(
                f"Failed to persist generated page {page_number} for project '{project_id}'."
            ) from exc

        return page

    async def optimize_existing_page(
        self,
        *,
        project_id: str,
        page_number: int,
        vue_code: str,
        change_description: str | None,
    ) -> ProjectPage:
        stmt: Select[tuple[ProjectPage]] = select(ProjectPage).where(
            ProjectPage.project_id == project_id,
            ProjectPage.page_number == page_number,
        )
        page = (await self.session.execute(stmt)).scalar_one_or_none()
        if page is None:
            raise PageNotFoundError(project_id, page_number)

        self._append_version_snapshot(
            page,
            vue_code=vue_code,
            status=PageStatus.GENERATED,
            change_description=change_description,
        )

        try:
            await self.session.commit()
            await self.session.refresh(page)
        except SQLAlchemyError as exc:
            await self.session.rollback()
            raise PageStorageError(
                f"Failed to persist optimized page {page_number} for project '{project_id}'."
            ) from exc

        return page

    async def insert_generated_page_after(
        self,
        *,
        project_id: str,
        after_page_number: int,
        outline_page: OutlinePageSchema | dict[str, Any],
        vue_code: str,
        status: PageStatus = PageStatus.GENERATED,
        change_description: str | None = "Generated by page generator.",
    ) -> ProjectPage:
        project = await self._get_project_for_mutation(project_id=project_id)
        total_pages = self._resolve_logical_total_pages(project)
        self._validate_logical_page_number(project_id=project_id, page_number=after_page_number, total_pages=total_pages)

        normalized_outline_page = (
            outline_page
            if isinstance(outline_page, OutlinePageSchema)
            else OutlinePageSchema.model_validate(outline_page)
        )
        inserted_page_number = after_page_number + 1
        logical_outline_pages = self._build_logical_outline_pages(project=project, total_pages=total_pages)

        try:
            await self._shift_project_pages_after(project.pages, after_page_number)
            await self._shift_chat_messages_after(project_id=project_id, page_number=after_page_number)
            self._write_project_outline(
                project=project,
                outline_pages=[
                    *logical_outline_pages[:after_page_number],
                    self._serialize_outline_page(normalized_outline_page, page_number=inserted_page_number),
                    *logical_outline_pages[after_page_number:],
                ],
            )
            page = ProjectPage(
                project_id=project_id,
                page_number=inserted_page_number,
                title=normalized_outline_page.title,
                page_type=normalized_outline_page.type,
                vue_code=vue_code,
                status=status,
                version=1,
            )
            self.session.add(page)
            self.session.add(
                PageVersion(
                    page=page,
                    version=1,
                    vue_code=vue_code,
                    change_description=change_description,
                )
            )
            await self.session.commit()
            await self.session.refresh(page)
        except SQLAlchemyError as exc:
            await self.session.rollback()
            raise PageStorageError(
                f"Failed to insert a new page after page {after_page_number} for project '{project_id}'."
            ) from exc

        await self.sync_preview_slides(project_id=project_id)
        return page

    async def duplicate_page(
        self,
        *,
        project_id: str,
        page_number: int,
    ) -> ProjectPage:
        project = await self._get_project_for_mutation(project_id=project_id, include_versions=True)
        total_pages = self._resolve_logical_total_pages(project)
        self._validate_logical_page_number(project_id=project_id, page_number=page_number, total_pages=total_pages)

        source_page = self._find_page(project.pages, page_number)
        if source_page is None or not str(source_page.vue_code or "").strip():
            raise PageNotFoundError(project_id, page_number)

        source_versions = list(source_page.versions)
        source_page_payload = {
            "page_type": source_page.page_type,
            "status": source_page.status,
            "title": source_page.title,
            "version": source_page.version,
            "vue_code": source_page.vue_code,
        }
        logical_outline_pages = self._build_logical_outline_pages(project=project, total_pages=total_pages)
        inserted_page_number = page_number + 1
        duplicated_outline_page = deepcopy(logical_outline_pages[page_number - 1])

        try:
            source_messages = await self._list_page_messages(project_id=project_id, page_numbers=[page_number])
            await self._shift_project_pages_after(project.pages, page_number)
            await self._shift_chat_messages_after(project_id=project_id, page_number=page_number)
            self._write_project_outline(
                project=project,
                outline_pages=[
                    *logical_outline_pages[:page_number],
                    {**duplicated_outline_page, "page_number": inserted_page_number},
                    *logical_outline_pages[page_number:],
                ],
            )

            duplicated_page = ProjectPage(
                project_id=project_id,
                page_number=inserted_page_number,
                title=source_page_payload["title"],
                page_type=source_page_payload["page_type"],
                vue_code=source_page_payload["vue_code"],
                status=source_page_payload["status"],
                version=source_page_payload["version"],
            )
            self.session.add(duplicated_page)
            await self.session.flush()

            for source_version in source_versions:
                self.session.add(
                    PageVersion(
                        page_id=duplicated_page.id,
                        version=source_version.version,
                        vue_code=source_version.vue_code,
                        change_description=source_version.change_description,
                        created_at=getattr(source_version, "created_at", None),
                    )
                )

            for source_message in source_messages:
                self.session.add(
                    ChatMessage(
                        project_id=project_id,
                        page_number=inserted_page_number,
                        role=source_message.role,
                        content=source_message.content,
                        message_type=source_message.message_type,
                        metadata_json=deepcopy(source_message.metadata_json),
                        created_at=getattr(source_message, "created_at", None),
                    )
                )

            await self.session.commit()
            await self.session.refresh(duplicated_page)
        except SQLAlchemyError as exc:
            await self.session.rollback()
            raise PageStorageError(
                f"Failed to duplicate page {page_number} for project '{project_id}'."
            ) from exc

        await self.sync_preview_slides(project_id=project_id)
        return duplicated_page

    async def delete_page(
        self,
        *,
        project_id: str,
        page_number: int,
    ) -> None:
        project = await self._get_project_for_mutation(project_id=project_id)
        total_pages = self._resolve_logical_total_pages(project)
        self._validate_logical_page_number(project_id=project_id, page_number=page_number, total_pages=total_pages)

        if total_pages <= 1:
            raise PageMutationValidationError("Cannot delete the last remaining page.")

        target_page = self._find_page(project.pages, page_number)
        logical_outline_pages = self._build_logical_outline_pages(project=project, total_pages=total_pages)

        try:
            if target_page is not None:
                await self.session.delete(target_page)

            await self._delete_and_shift_chat_messages(project_id=project_id, deleted_page_number=page_number)
            await self._shift_project_pages_after_delete(project.pages, page_number)
            self._write_project_outline(
                project=project,
                outline_pages=[
                    *logical_outline_pages[: page_number - 1],
                    *logical_outline_pages[page_number:],
                ],
            )
            await self.session.commit()
        except SQLAlchemyError as exc:
            await self.session.rollback()
            raise PageStorageError(
                f"Failed to delete page {page_number} for project '{project_id}'."
            ) from exc

        await self.sync_preview_slides(project_id=project_id)

    async def reorder_pages(
        self,
        *,
        project_id: str,
        ordered_page_numbers: list[int],
    ) -> None:
        project = await self._get_project_for_mutation(project_id=project_id)
        total_pages = self._resolve_logical_total_pages(project)
        expected_page_numbers = list(range(1, total_pages + 1))

        if len(ordered_page_numbers) != total_pages or sorted(ordered_page_numbers) != expected_page_numbers:
            raise InvalidPageOrderError(f"Page order must be a full permutation of 1..{total_pages}.")

        mapping = {
            old_page_number: new_index
            for new_index, old_page_number in enumerate(ordered_page_numbers, start=1)
            if old_page_number != new_index
        }
        if not mapping:
            await self.sync_preview_slides(project_id=project_id)
            return

        try:
            logical_outline_pages = self._build_logical_outline_pages(project=project, total_pages=total_pages)
            await self._apply_page_number_mapping(project.pages, mapping)
            await self._reassign_chat_message_page_numbers(project_id=project_id, mapping=mapping)
            self._write_project_outline(
                project=project,
                outline_pages=[
                    deepcopy(logical_outline_pages[old_page_number - 1])
                    for old_page_number in ordered_page_numbers
                ],
            )
            await self.session.commit()
        except SQLAlchemyError as exc:
            await self.session.rollback()
            raise PageStorageError(f"Failed to reorder pages for project '{project_id}'.") from exc

        await self.sync_preview_slides(project_id=project_id)

    async def list_page_versions(
        self,
        *,
        project_id: str,
        page_number: int,
    ) -> list[PageVersion]:
        page = await self._get_page_or_raise(project_id=project_id, page_number=page_number)
        stmt: Select[tuple[PageVersion]] = (
            select(PageVersion)
            .where(PageVersion.page_id == page.id)
            .order_by(PageVersion.version.desc(), PageVersion.created_at.desc())
        )
        return list((await self.session.execute(stmt)).scalars().all())

    async def rollback_page_to_version(
        self,
        *,
        project_id: str,
        page_number: int,
        target_version: int,
    ) -> ProjectPage:
        page = await self._get_page_or_raise(project_id=project_id, page_number=page_number)
        target = await self._get_page_version_or_raise(
            page_id=page.id,
            project_id=project_id,
            page_number=page_number,
            version=target_version,
        )
        await self._ensure_current_version_snapshot(page)
        self._append_version_snapshot(
            page,
            vue_code=target.vue_code,
            status=PageStatus.GENERATED,
            change_description=f"回滚到 v{target_version}",
        )

        try:
            await self.session.commit()
            await self.session.refresh(page)
        except SQLAlchemyError as exc:
            await self.session.rollback()
            raise PageStorageError(
                f"Failed to rollback page {page_number} for project '{project_id}'."
            ) from exc

        return page

    async def confirm_page(
        self,
        *,
        project_id: str,
        page_number: int,
    ) -> ProjectPage:
        stmt: Select[tuple[ProjectPage]] = select(ProjectPage).where(
            ProjectPage.project_id == project_id,
            ProjectPage.page_number == page_number,
        )
        page = (await self.session.execute(stmt)).scalar_one_or_none()
        if page is None:
            raise PageNotFoundError(project_id, page_number)

        page.status = PageStatus.CONFIRMED

        try:
            await self.session.commit()
            await self.session.refresh(page)
        except SQLAlchemyError as exc:
            await self.session.rollback()
            raise PageStorageError(
                f"Failed to confirm page {page_number} for project '{project_id}'."
            ) from exc

        return page

    def write_preview_slide(self, *, page_number: int, vue_code: str) -> Path:
        slides_dir = self._preview_slides_dir()
        target_path = self._preview_slide_path(page_number)

        if not target_path.is_relative_to(slides_dir):
            raise PreviewSlideWriteError(f"Refusing to write preview slide outside '{slides_dir}'.")

        try:
            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.write_text(vue_code, encoding="utf-8")
        except OSError as exc:
            raise PreviewSlideWriteError(f"Failed to write preview slide '{target_path}'.") from exc

        return target_path

    def write_version_preview_slide(self, *, page_number: int, vue_code: str) -> Path:
        slides_dir = self._preview_slides_dir()
        target_path = (slides_dir / "version-preview.vue").resolve()

        if not target_path.is_relative_to(slides_dir):
            raise PreviewSlideWriteError(f"Refusing to write version preview outside '{slides_dir}'.")

        try:
            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.write_text(vue_code, encoding="utf-8")
        except OSError as exc:
            raise PreviewSlideWriteError(f"Failed to write version preview slide '{target_path}'.") from exc

        return target_path

    async def sync_preview_slides(self, *, project_id: str) -> None:
        slides_dir = self._preview_slides_dir()
        slides_dir.mkdir(parents=True, exist_ok=True)
        current_pages = list(
            (
                await self.session.execute(
                    select(ProjectPage)
                    .where(ProjectPage.project_id == project_id)
                    .order_by(ProjectPage.page_number.asc())
                )
            )
            .scalars()
            .all()
        )
        expected_page_numbers = {
            int(page.page_number)
            for page in current_pages
            if str(page.vue_code or "").strip()
        }

        try:
            for page in current_pages:
                vue_code = str(page.vue_code or "")
                if not vue_code.strip():
                    continue
                self.write_preview_slide(page_number=int(page.page_number), vue_code=vue_code)

            for path in slides_dir.glob("page-*.vue"):
                page_number = self._parse_preview_slide_page_number(path)
                if page_number is None or page_number not in expected_page_numbers:
                    path.unlink(missing_ok=True)
        except OSError as exc:
            raise PreviewSlideWriteError(
                f"Failed to synchronize preview slides for project '{project_id}'."
            ) from exc

    def _append_version_snapshot(
        self,
        page: ProjectPage,
        *,
        vue_code: str,
        status: PageStatus,
        change_description: str | None,
    ) -> None:
        next_version = int(page.version) + 1
        page.vue_code = vue_code
        page.status = status
        page.version = next_version
        self.session.add(
            PageVersion(
                page_id=page.id,
                version=next_version,
                vue_code=vue_code,
                change_description=change_description,
            )
        )

    async def _get_page_or_raise(self, *, project_id: str, page_number: int) -> ProjectPage:
        stmt: Select[tuple[ProjectPage]] = select(ProjectPage).where(
            ProjectPage.project_id == project_id,
            ProjectPage.page_number == page_number,
        )
        page = (await self.session.execute(stmt)).scalar_one_or_none()
        if page is None:
            raise PageNotFoundError(project_id, page_number)
        return page

    async def _get_page_version_or_raise(
        self,
        *,
        page_id: str,
        project_id: str,
        page_number: int,
        version: int,
    ) -> PageVersion:
        stmt: Select[tuple[PageVersion]] = select(PageVersion).where(
            PageVersion.page_id == page_id,
            PageVersion.version == version,
        )
        page_version = (await self.session.execute(stmt)).scalar_one_or_none()
        if page_version is None:
            raise PageVersionNotFoundError(project_id, page_number, version)
        return page_version

    async def _ensure_current_version_snapshot(self, page: ProjectPage) -> None:
        stmt: Select[tuple[PageVersion]] = select(PageVersion).where(
            PageVersion.page_id == page.id,
            PageVersion.version == page.version,
        )
        existing_version = (await self.session.execute(stmt)).scalar_one_or_none()
        if existing_version is not None:
            return

        self.session.add(
            PageVersion(
                page_id=page.id,
                version=int(page.version),
                vue_code=str(page.vue_code or ""),
                change_description=f"回滚前补建 v{int(page.version)} 备份",
            )
        )

    async def _get_project_for_mutation(
        self,
        *,
        project_id: str,
        include_versions: bool = False,
    ) -> Project:
        page_loader = selectinload(Project.pages)
        if include_versions:
            page_loader = page_loader.selectinload(ProjectPage.versions)

        stmt: Select[tuple[Project]] = (
            select(Project)
            .options(page_loader)
            .where(Project.id == project_id)
        )
        project = (await self.session.execute(stmt)).scalar_one_or_none()
        if project is None:
            raise PageMutationValidationError(f"Project '{project_id}' was not found.")
        return project

    async def _shift_project_pages_after(self, pages: list[ProjectPage], page_number: int) -> None:
        mapping = {
            int(page.page_number): int(page.page_number) + 1
            for page in pages
            if int(page.page_number) > page_number
        }
        await self._apply_page_number_mapping(pages, mapping)

    async def _shift_project_pages_after_delete(self, pages: list[ProjectPage], page_number: int) -> None:
        mapping = {
            int(page.page_number): int(page.page_number) - 1
            for page in pages
            if int(page.page_number) > page_number
        }
        await self._apply_page_number_mapping(pages, mapping)

    async def _apply_page_number_mapping(self, pages: list[ProjectPage], mapping: dict[int, int]) -> None:
        pages_to_move = [page for page in pages if int(page.page_number) in mapping]
        if not pages_to_move:
            return

        original_page_numbers = {page.id: int(page.page_number) for page in pages_to_move}
        max_page_number = max([*mapping.keys(), *mapping.values(), *original_page_numbers.values()], default=0)
        page_number_offset = max_page_number + self._PAGE_NUMBER_OFFSET_BUFFER

        for page in pages_to_move:
            page.page_number = original_page_numbers[page.id] + page_number_offset
        await self.session.flush()

        for page in pages_to_move:
            page.page_number = mapping[original_page_numbers[page.id]]

    async def _shift_chat_messages_after(self, *, project_id: str, page_number: int) -> None:
        messages = await self._list_page_messages_after(project_id=project_id, page_number=page_number)
        for message in messages:
            if message.page_number is not None:
                message.page_number = int(message.page_number) + 1

    async def _delete_and_shift_chat_messages(self, *, project_id: str, deleted_page_number: int) -> None:
        messages = await self._list_page_messages_after(project_id=project_id, page_number=deleted_page_number - 1)
        for message in messages:
            if message.page_number == deleted_page_number:
                await self.session.delete(message)
                continue
            if message.page_number is not None and int(message.page_number) > deleted_page_number:
                message.page_number = int(message.page_number) - 1

    async def _reassign_chat_message_page_numbers(self, *, project_id: str, mapping: dict[int, int]) -> None:
        messages = await self._list_page_messages(project_id=project_id, page_numbers=list(mapping.keys()))
        for message in messages:
            if message.page_number is None:
                continue
            message.page_number = mapping[int(message.page_number)]

    async def _list_page_messages_after(self, *, project_id: str, page_number: int) -> list[ChatMessage]:
        stmt: Select[tuple[ChatMessage]] = (
            select(ChatMessage)
            .where(
                ChatMessage.project_id == project_id,
                ChatMessage.page_number.is_not(None),
                ChatMessage.page_number > page_number,
            )
            .order_by(ChatMessage.page_number.asc(), ChatMessage.created_at.asc(), ChatMessage.id.asc())
        )
        return list((await self.session.execute(stmt)).scalars().all())

    async def _list_page_messages(self, *, project_id: str, page_numbers: list[int]) -> list[ChatMessage]:
        if not page_numbers:
            return []

        stmt: Select[tuple[ChatMessage]] = (
            select(ChatMessage)
            .where(
                ChatMessage.project_id == project_id,
                ChatMessage.page_number.in_(page_numbers),
            )
            .order_by(ChatMessage.page_number.asc(), ChatMessage.created_at.asc(), ChatMessage.id.asc())
        )
        return list((await self.session.execute(stmt)).scalars().all())

    def _find_page(self, pages: list[ProjectPage], page_number: int) -> ProjectPage | None:
        for page in pages:
            if int(page.page_number) == page_number:
                return page
        return None

    def _resolve_logical_total_pages(self, project: Project) -> int:
        outline_pages = self._outline_pages_from_project(project)
        highest_outline_page_number = max(
            (
                int(page.get("page_number"))
                for page in outline_pages
                if isinstance(page, dict) and isinstance(page.get("page_number"), int)
            ),
            default=0,
        )
        highest_generated_page_number = max((int(page.page_number) for page in project.pages), default=0)
        return max(
            int(getattr(project, "total_pages", 0) or 0),
            len(outline_pages),
            highest_outline_page_number,
            highest_generated_page_number,
        )

    def _validate_logical_page_number(self, *, project_id: str, page_number: int, total_pages: int) -> None:
        if page_number < 1 or page_number > total_pages:
            raise PageNotFoundError(project_id, page_number)

    def _build_logical_outline_pages(self, *, project: Project, total_pages: int) -> list[dict[str, Any]]:
        existing_outline_page_map = {
            int(page["page_number"]): deepcopy(page)
            for page in self._outline_pages_from_project(project)
            if isinstance(page, dict) and isinstance(page.get("page_number"), int)
        }
        generated_page_map = {int(page.page_number): page for page in project.pages}

        return [
            self._materialize_outline_page(
                page_number=page_number,
                outline_page=existing_outline_page_map.get(page_number),
                generated_page=generated_page_map.get(page_number),
            )
            for page_number in range(1, total_pages + 1)
        ]

    def _write_project_outline(self, *, project: Project, outline_pages: list[dict[str, Any]]) -> None:
        existing_outline = project.outline if isinstance(project.outline, dict) else {}
        normalized_outline_pages = [
            self._serialize_outline_page(page, page_number=index)
            for index, page in enumerate(outline_pages, start=1)
        ]
        project.outline = {
            "title": self._normalized_text(existing_outline.get("title")) or getattr(project, "name", "未命名项目"),
            "theme_suggestion": self._normalized_text(existing_outline.get("theme_suggestion")) or "warm-paper",
            "total_pages": len(normalized_outline_pages),
            "pages": normalized_outline_pages,
        }
        project.total_pages = len(normalized_outline_pages)

    def _materialize_outline_page(
        self,
        *,
        page_number: int,
        outline_page: dict[str, Any] | None,
        generated_page: ProjectPage | None,
    ) -> dict[str, Any]:
        normalized_outline_page = outline_page if isinstance(outline_page, dict) else {}
        title = (
            self._normalized_text(normalized_outline_page.get("title"))
            or self._normalized_text(getattr(generated_page, "title", None))
            or f"第 {page_number} 页"
        )
        page_type = (
            self._normalized_text(normalized_outline_page.get("type"))
            or self._normalized_text(getattr(generated_page, "page_type", None))
            or "content"
        )
        return {
            "page_number": page_number,
            "title": title,
            "type": page_type,
            "content_brief": self._normalized_text(normalized_outline_page.get("content_brief")) or title,
            "layout": self._normalized_text(normalized_outline_page.get("layout")) or "title-body",
            "data_refs": self._normalized_string_list(normalized_outline_page.get("data_refs")),
        }

    def _outline_pages_from_project(self, project: Project) -> list[dict[str, Any]]:
        outline = project.outline
        if not isinstance(outline, dict):
            return []

        pages = outline.get("pages")
        if not isinstance(pages, list):
            return []

        return [page for page in pages if isinstance(page, dict)]

    def _serialize_outline_page(self, outline_page: OutlinePageSchema | dict[str, Any], *, page_number: int) -> dict[str, Any]:
        normalized_page = (
            outline_page if isinstance(outline_page, OutlinePageSchema) else OutlinePageSchema.model_validate(outline_page)
        )
        return {
            "page_number": page_number,
            "title": normalized_page.title,
            "type": normalized_page.type,
            "content_brief": normalized_page.content_brief,
            "layout": normalized_page.layout,
            "data_refs": list(normalized_page.data_refs),
        }

    def _preview_slides_dir(self) -> Path:
        return self.settings.preview_slides_dir_path.resolve()

    def _preview_slide_path(self, page_number: int) -> Path:
        return (self._preview_slides_dir() / f"page-{page_number}.vue").resolve()

    def _parse_preview_slide_page_number(self, path: Path) -> int | None:
        stem = path.stem
        if not stem.startswith("page-"):
            return None

        raw_page_number = stem.removeprefix("page-").strip()
        if not raw_page_number.isdigit():
            return None
        return int(raw_page_number)

    def build_page_generation_context(
        self,
        *,
        project: Any,
        outline_page: OutlinePageSchema | dict[str, Any],
        parsed_contents: list[dict[str, Any]],
    ) -> dict[str, Any]:
        normalized_page = outline_page if isinstance(outline_page, OutlinePageSchema) else OutlinePageSchema.model_validate(outline_page)
        scored_sources = sorted(
            (
                (self._score_source(normalized_page=normalized_page, source=source), source)
                for source in parsed_contents
            ),
            key=lambda item: item[0],
            reverse=True,
        )
        selected_sources = [self._compact_source(source) for score, source in scored_sources if score > 0][:3]

        if not selected_sources:
            selected_sources = [self._compact_source(source) for source in parsed_contents[:2]]

        return {
            "project": {
                "id": getattr(project, "id", None),
                "name": getattr(project, "name", None),
                "description": getattr(project, "description", None),
            },
            "page": normalized_page.model_dump(mode="json"),
            "selection_signals": {
                "data_refs": list(normalized_page.data_refs),
                "page_keywords": self._page_keywords(normalized_page),
                "selected_source_count": len(selected_sources),
                "available_source_count": len(parsed_contents),
            },
            "selected_sources": selected_sources,
        }

    def _score_source(self, *, normalized_page: OutlinePageSchema, source: dict[str, Any]) -> int:
        score = 0
        file_name = self._normalized_text(source.get("file_name") or source.get("original_name"))
        haystacks = [
            file_name.lower(),
            self._normalized_text(source.get("summary")).lower(),
            self._normalized_text(source.get("text_content") or source.get("text_excerpt")).lower(),
            " ".join(self._normalized_string_list(source.get("key_points"))).lower(),
        ]

        for data_ref in normalized_page.data_refs:
            normalized_ref = data_ref.strip().lower()
            if not normalized_ref:
                continue
            if normalized_ref == file_name.lower():
                score += 6
            elif any(normalized_ref in haystack for haystack in haystacks):
                score += 4

        for keyword in self._page_keywords(normalized_page):
            if any(keyword in haystack for haystack in haystacks):
                score += 1

        if normalized_page.type in {"data", "comparison"} and source.get("structured_data"):
            score += 2

        return score

    def _compact_source(self, source: dict[str, Any]) -> dict[str, Any]:
        return {
            "file_id": source.get("file_id") or source.get("id"),
            "file_name": source.get("file_name") or source.get("original_name"),
            "file_type": source.get("file_type"),
            "summary": self._normalized_text(source.get("summary")),
            "key_points": self._normalized_string_list(source.get("key_points"))[:6],
            "text_excerpt": self._truncate_text(source.get("text_content") or source.get("text_excerpt"), limit=1200),
            "structured_data": self._compact_structured_data(source.get("structured_data")),
        }

    def _compact_structured_data(self, value: Any) -> dict[str, Any]:
        if not isinstance(value, dict):
            return {}

        compacted: dict[str, Any] = {}
        for key in list(value.keys())[:8]:
            raw_item = value[key]
            if isinstance(raw_item, (str, int, float, bool)) or raw_item is None:
                compacted[key] = raw_item
                continue

            if isinstance(raw_item, list):
                compacted[key] = raw_item[:5]
                continue

            if isinstance(raw_item, dict):
                compacted[key] = {nested_key: raw_item[nested_key] for nested_key in list(raw_item.keys())[:5]}

        return compacted

    def _page_keywords(self, normalized_page: OutlinePageSchema) -> list[str]:
        keywords = [
            normalized_page.title.lower(),
            normalized_page.type.lower(),
            normalized_page.layout.lower(),
        ]
        keywords.extend(ref.lower() for ref in normalized_page.data_refs if ref.strip())
        return [keyword for keyword in keywords if keyword]

    def _truncate_text(self, value: Any, *, limit: int) -> str:
        text = self._normalized_text(value)
        if len(text) <= limit:
            return text
        return f"{text[: limit - 3].rstrip()}..."

    def _normalized_text(self, value: Any) -> str:
        if isinstance(value, str):
            return value.strip()
        return ""

    def _normalized_string_list(self, value: Any) -> list[str]:
        if not isinstance(value, list):
            return []

        normalized: list[str] = []
        for item in value:
            if isinstance(item, str):
                stripped = item.strip()
                if stripped:
                    normalized.append(stripped)
        return normalized
