from __future__ import annotations

from pathlib import Path
from typing import Any

from sqlalchemy import Select, select
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import Settings
from app.models import PageVersion, ProjectPage
from app.models.enums import PageStatus
from app.schemas.project import OutlinePageSchema


class PageServiceError(Exception):
    """Base exception for page generation persistence failures."""


class PageStorageError(PageServiceError):
    """Raised when page persistence to the database fails."""


class PreviewSlideWriteError(PageServiceError):
    """Raised when a preview slide file cannot be written safely."""


class PageService:
    def __init__(self, session: AsyncSession, settings: Settings):
        self.session = session
        self.settings = settings

    async def upsert_generated_page(
        self,
        *,
        project_id: str,
        page_number: int,
        title: str | None,
        page_type: str | None,
        vue_code: str,
        status: PageStatus = PageStatus.GENERATED,
        change_description: str | None = "Generated by page generator.",
    ) -> ProjectPage:
        stmt: Select[tuple[ProjectPage]] = select(ProjectPage).where(
            ProjectPage.project_id == project_id,
            ProjectPage.page_number == page_number,
        )
        page = (await self.session.execute(stmt)).scalar_one_or_none()

        if page is None:
            page = ProjectPage(
                project_id=project_id,
                page_number=page_number,
                title=title,
                page_type=page_type,
                vue_code=vue_code,
                status=status,
                version=1,
            )
            self.session.add(page)
            self.session.add(
                PageVersion(
                    page=page,
                    version=1,
                    vue_code=vue_code,
                    change_description=change_description,
                )
            )
        else:
            next_version = int(page.version) + 1
            page.title = title
            page.page_type = page_type
            page.vue_code = vue_code
            page.status = status
            page.version = next_version
            self.session.add(
                PageVersion(
                    page_id=page.id,
                    version=next_version,
                    vue_code=vue_code,
                    change_description=change_description,
                )
            )

        try:
            await self.session.commit()
            await self.session.refresh(page)
        except SQLAlchemyError as exc:
            await self.session.rollback()
            raise PageStorageError(
                f"Failed to persist generated page {page_number} for project '{project_id}'."
            ) from exc

        return page

    def write_preview_slide(self, *, page_number: int, vue_code: str) -> Path:
        slides_dir = self.settings.preview_slides_dir_path.resolve()
        target_path = (slides_dir / f"page-{page_number}.vue").resolve()

        if not target_path.is_relative_to(slides_dir):
            raise PreviewSlideWriteError(f"Refusing to write preview slide outside '{slides_dir}'.")

        try:
            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.write_text(vue_code, encoding="utf-8")
        except OSError as exc:
            raise PreviewSlideWriteError(f"Failed to write preview slide '{target_path}'.") from exc

        return target_path

    def build_page_generation_context(
        self,
        *,
        project: Any,
        outline_page: OutlinePageSchema | dict[str, Any],
        parsed_contents: list[dict[str, Any]],
    ) -> dict[str, Any]:
        normalized_page = outline_page if isinstance(outline_page, OutlinePageSchema) else OutlinePageSchema.model_validate(outline_page)
        scored_sources = sorted(
            (
                (self._score_source(normalized_page=normalized_page, source=source), source)
                for source in parsed_contents
            ),
            key=lambda item: item[0],
            reverse=True,
        )
        selected_sources = [self._compact_source(source) for score, source in scored_sources if score > 0][:3]

        if not selected_sources:
            selected_sources = [self._compact_source(source) for source in parsed_contents[:2]]

        return {
            "project": {
                "id": getattr(project, "id", None),
                "name": getattr(project, "name", None),
                "description": getattr(project, "description", None),
            },
            "page": normalized_page.model_dump(mode="json"),
            "selection_signals": {
                "data_refs": list(normalized_page.data_refs),
                "page_keywords": self._page_keywords(normalized_page),
                "selected_source_count": len(selected_sources),
                "available_source_count": len(parsed_contents),
            },
            "selected_sources": selected_sources,
        }

    def _score_source(self, *, normalized_page: OutlinePageSchema, source: dict[str, Any]) -> int:
        score = 0
        file_name = self._normalized_text(source.get("file_name") or source.get("original_name"))
        haystacks = [
            file_name.lower(),
            self._normalized_text(source.get("summary")).lower(),
            self._normalized_text(source.get("text_content") or source.get("text_excerpt")).lower(),
            " ".join(self._normalized_string_list(source.get("key_points"))).lower(),
        ]

        for data_ref in normalized_page.data_refs:
            normalized_ref = data_ref.strip().lower()
            if not normalized_ref:
                continue
            if normalized_ref == file_name.lower():
                score += 6
            elif any(normalized_ref in haystack for haystack in haystacks):
                score += 4

        for keyword in self._page_keywords(normalized_page):
            if any(keyword in haystack for haystack in haystacks):
                score += 1

        if normalized_page.type in {"data", "comparison"} and source.get("structured_data"):
            score += 2

        return score

    def _compact_source(self, source: dict[str, Any]) -> dict[str, Any]:
        return {
            "file_id": source.get("file_id") or source.get("id"),
            "file_name": source.get("file_name") or source.get("original_name"),
            "file_type": source.get("file_type"),
            "summary": self._normalized_text(source.get("summary")),
            "key_points": self._normalized_string_list(source.get("key_points"))[:6],
            "text_excerpt": self._truncate_text(source.get("text_content") or source.get("text_excerpt"), limit=1200),
            "structured_data": self._compact_structured_data(source.get("structured_data")),
        }

    def _compact_structured_data(self, value: Any) -> dict[str, Any]:
        if not isinstance(value, dict):
            return {}

        compacted: dict[str, Any] = {}
        for key in list(value.keys())[:8]:
            raw_item = value[key]
            if isinstance(raw_item, (str, int, float, bool)) or raw_item is None:
                compacted[key] = raw_item
                continue

            if isinstance(raw_item, list):
                compacted[key] = raw_item[:5]
                continue

            if isinstance(raw_item, dict):
                compacted[key] = {nested_key: raw_item[nested_key] for nested_key in list(raw_item.keys())[:5]}

        return compacted

    def _page_keywords(self, normalized_page: OutlinePageSchema) -> list[str]:
        keywords = [
            normalized_page.title.lower(),
            normalized_page.type.lower(),
            normalized_page.layout.lower(),
        ]
        keywords.extend(ref.lower() for ref in normalized_page.data_refs if ref.strip())
        return [keyword for keyword in keywords if keyword]

    def _truncate_text(self, value: Any, *, limit: int) -> str:
        text = self._normalized_text(value)
        if len(text) <= limit:
            return text
        return f"{text[: limit - 3].rstrip()}..."

    def _normalized_text(self, value: Any) -> str:
        if isinstance(value, str):
            return value.strip()
        return ""

    def _normalized_string_list(self, value: Any) -> list[str]:
        if not isinstance(value, list):
            return []

        normalized: list[str] = []
        for item in value:
            if isinstance(item, str):
                stripped = item.strip()
                if stripped:
                    normalized.append(stripped)
        return normalized
