from __future__ import annotations

from pathlib import Path

from app.config import Settings
from app.schemas import DEFAULT_THEME_ID, ThemeConfig
from app.schemas.theme import resolve_theme_id


class ThemeServiceError(Exception):
    """Base exception for theme service failures."""


class ThemeValidationError(ThemeServiceError):
    """Raised when a theme id or shape is invalid."""


class ThemeWriteError(ThemeServiceError):
    """Raised when the preview theme file cannot be written."""


APTOS_TITLE_FONT = '"Aptos Display", "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif'
APTOS_BODY_FONT = '"Aptos", "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif'


class ThemeService:
    def __init__(self, settings: Settings):
        self.settings = settings
        self._presets = {theme.id: theme for theme in self._build_presets()}

    def list_presets(self) -> list[ThemeConfig]:
        return [theme.model_copy(deep=True) for theme in self._presets.values()]

    def resolve_theme(self, raw_theme: ThemeConfig | dict[str, object] | None) -> ThemeConfig:
        theme_id = resolve_theme_id(raw_theme)
        preset = self._presets.get(theme_id)

        if preset is None:
            raise ThemeValidationError(f"Unsupported theme id '{theme_id}'.")

        return preset.model_copy(deep=True)

    def render_css_variables(self, raw_theme: ThemeConfig | dict[str, object] | None) -> str:
        theme = self.resolve_theme(raw_theme)
        variable_lines = (
            ("--slide-primary", theme.colors.primary),
            ("--slide-secondary", theme.colors.secondary),
            ("--slide-accent", theme.colors.accent),
            ("--slide-bg", theme.colors.background),
            ("--slide-surface", theme.colors.surface),
            ("--slide-surface-strong", theme.colors.surfaceStrong),
            ("--slide-surface-soft", theme.colors.surfaceSoft),
            ("--slide-text", theme.colors.text),
            ("--slide-text-secondary", theme.colors.textSecondary),
            ("--slide-border", theme.colors.border),
            ("--slide-danger", theme.colors.danger),
            ("--slide-danger-soft", theme.colors.dangerSoft),
            ("--slide-neutral-soft", theme.colors.neutralSoft),
            ("--slide-font-title", theme.fonts.title),
            ("--slide-font-body", theme.fonts.body),
            ("--slide-radius-xl", theme.borderRadius.xl),
            ("--slide-radius-lg", theme.borderRadius.lg),
            ("--slide-radius-md", theme.borderRadius.md),
            ("--slide-shadow", theme.shadows.default),
            ("--slide-shadow-soft", theme.shadows.soft),
            ("--slide-shadow-card", theme.shadows.card),
            ("--slide-primary-soft", theme.colors.primarySoft),
            ("--slide-secondary-soft", theme.colors.secondarySoft),
            ("--slide-accent-soft", theme.colors.accentSoft),
            ("--slide-grid-line", theme.colors.gridLine),
        )
        root_body = "\n".join(f"  {name}: {value};" for name, value in variable_lines)
        color_scheme = "dark" if theme.appearance == "dark" else "light"

        return (
            "/* Auto-generated by PPT Studio. Preview theme changes will overwrite this file. */\n"
            f"/* theme: {theme.id} ({theme.label}) */\n"
            ":root {\n"
            f"  color-scheme: {color_scheme};\n\n"
            f"{root_body}\n"
            "}\n\n"
            "*,\n"
            "*::before,\n"
            "*::after {\n"
            "  box-sizing: border-box;\n"
            "}\n\n"
            "html,\n"
            "body,\n"
            "#app {\n"
            "  min-width: 100%;\n"
            "  min-height: 100%;\n"
            "  margin: 0;\n"
            "}\n\n"
            "body {\n"
            "  font-family: var(--slide-font-body);\n"
            "  color: var(--slide-text);\n"
            "  background:\n"
            "    radial-gradient(circle at top left, var(--slide-secondary-soft) 0%, transparent 34%),\n"
            "    radial-gradient(circle at 85% 20%, var(--slide-accent-soft) 0%, transparent 18%),\n"
            "    linear-gradient(\n"
            "      180deg,\n"
            "      color-mix(in srgb, var(--slide-bg) 84%, var(--slide-surface-strong) 16%) 0%,\n"
            "      var(--slide-bg) 58%,\n"
            "      color-mix(in srgb, var(--slide-surface) 68%, var(--slide-bg) 32%) 100%\n"
            "    );\n"
            "}\n\n"
            "button,\n"
            "input,\n"
            "select,\n"
            "textarea {\n"
            "  font: inherit;\n"
            "}\n"
        )

    def write_preview_theme(self, raw_theme: ThemeConfig | dict[str, object] | None) -> Path:
        theme = self.resolve_theme(raw_theme)
        target_path = self.settings.preview_theme_file_path.resolve()
        css_content = self.render_css_variables(theme)

        try:
            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.write_text(css_content, encoding="utf-8")
        except OSError as exc:
            raise ThemeWriteError(f"Failed to write preview theme file '{target_path}'.") from exc

        return target_path

    def _build_presets(self) -> tuple[ThemeConfig, ...]:
        return (
            ThemeConfig(
                id=DEFAULT_THEME_ID,
                label="温暖橙",
                description="延续当前暖色纸感预览风格，适合作为默认页面主题。",
                appearance="light",
                colors={
                    "primary": "#68a67d",
                    "secondary": "#8fbf9f",
                    "accent": "#f18f01",
                    "background": "#f5ecd7",
                    "surface": "#ebe2cd",
                    "surfaceStrong": "rgba(255, 251, 243, 0.92)",
                    "surfaceSoft": "rgba(255, 248, 237, 0.76)",
                    "text": "#353535",
                    "textSecondary": "#5f5f5f",
                    "border": "#c2baa6",
                    "danger": "#c66d4d",
                    "dangerSoft": "rgba(198, 109, 77, 0.14)",
                    "neutralSoft": "rgba(95, 95, 95, 0.12)",
                    "primarySoft": "rgba(104, 166, 125, 0.18)",
                    "secondarySoft": "rgba(143, 191, 159, 0.24)",
                    "accentSoft": "rgba(241, 143, 1, 0.16)",
                    "gridLine": "rgba(131, 53, 0, 0.08)",
                },
                fonts={
                    "title": APTOS_TITLE_FONT,
                    "body": APTOS_BODY_FONT,
                },
                borderRadius={
                    "xl": "32px",
                    "lg": "24px",
                    "md": "18px",
                },
                shadows={
                    "default": "0 28px 60px rgba(111, 87, 48, 0.16)",
                    "soft": "0 14px 32px rgba(111, 87, 48, 0.12)",
                    "card": "0 18px 40px rgba(111, 87, 48, 0.14)",
                },
                animationStyle="calm",
            ),
            ThemeConfig(
                id="business-blue",
                label="商务蓝",
                description="浅底商务蓝主题，适合汇报、复盘和经营分析类页面。",
                appearance="light",
                colors={
                    "primary": "#3b6ea8",
                    "secondary": "#7ca9d8",
                    "accent": "#f0a431",
                    "background": "#eef4fb",
                    "surface": "#dfe8f4",
                    "surfaceStrong": "rgba(255, 255, 255, 0.9)",
                    "surfaceSoft": "rgba(244, 248, 252, 0.78)",
                    "text": "#233247",
                    "textSecondary": "#55657a",
                    "border": "#bfd0e2",
                    "danger": "#c66b58",
                    "dangerSoft": "rgba(198, 107, 88, 0.14)",
                    "neutralSoft": "rgba(85, 101, 122, 0.12)",
                    "primarySoft": "rgba(59, 110, 168, 0.18)",
                    "secondarySoft": "rgba(124, 169, 216, 0.22)",
                    "accentSoft": "rgba(240, 164, 49, 0.16)",
                    "gridLine": "rgba(59, 110, 168, 0.08)",
                },
                fonts={
                    "title": APTOS_TITLE_FONT,
                    "body": APTOS_BODY_FONT,
                },
                borderRadius={
                    "xl": "28px",
                    "lg": "22px",
                    "md": "16px",
                },
                shadows={
                    "default": "0 28px 60px rgba(59, 110, 168, 0.14)",
                    "soft": "0 14px 32px rgba(59, 110, 168, 0.1)",
                    "card": "0 18px 40px rgba(35, 50, 71, 0.12)",
                },
                animationStyle="minimal",
            ),
            ThemeConfig(
                id="fresh-green",
                label="清新绿",
                description="浅色清新绿主题，适合增长、可持续和团队协同内容。",
                appearance="light",
                colors={
                    "primary": "#4f9b74",
                    "secondary": "#96c7aa",
                    "accent": "#efb960",
                    "background": "#edf5ee",
                    "surface": "#dceadd",
                    "surfaceStrong": "rgba(251, 255, 250, 0.92)",
                    "surfaceSoft": "rgba(244, 250, 243, 0.78)",
                    "text": "#2e4237",
                    "textSecondary": "#5b6f62",
                    "border": "#bfd0c1",
                    "danger": "#bf6a55",
                    "dangerSoft": "rgba(191, 106, 85, 0.14)",
                    "neutralSoft": "rgba(91, 111, 98, 0.12)",
                    "primarySoft": "rgba(79, 155, 116, 0.18)",
                    "secondarySoft": "rgba(150, 199, 170, 0.22)",
                    "accentSoft": "rgba(239, 185, 96, 0.18)",
                    "gridLine": "rgba(79, 155, 116, 0.08)",
                },
                fonts={
                    "title": APTOS_TITLE_FONT,
                    "body": APTOS_BODY_FONT,
                },
                borderRadius={
                    "xl": "30px",
                    "lg": "22px",
                    "md": "16px",
                },
                shadows={
                    "default": "0 28px 60px rgba(79, 155, 116, 0.14)",
                    "soft": "0 14px 32px rgba(79, 155, 116, 0.1)",
                    "card": "0 18px 40px rgba(46, 66, 55, 0.12)",
                },
                animationStyle="calm",
            ),
            ThemeConfig(
                id="minimal-gray",
                label="极简灰",
                description="浅灰极简主题，适合信息密度高、强调秩序感的页面。",
                appearance="light",
                colors={
                    "primary": "#6b7480",
                    "secondary": "#b0b8c1",
                    "accent": "#c99752",
                    "background": "#f3f4f6",
                    "surface": "#e4e7eb",
                    "surfaceStrong": "rgba(255, 255, 255, 0.92)",
                    "surfaceSoft": "rgba(248, 249, 251, 0.8)",
                    "text": "#2f343b",
                    "textSecondary": "#686f79",
                    "border": "#cfd5dc",
                    "danger": "#c06158",
                    "dangerSoft": "rgba(192, 97, 88, 0.14)",
                    "neutralSoft": "rgba(104, 111, 121, 0.12)",
                    "primarySoft": "rgba(107, 116, 128, 0.16)",
                    "secondarySoft": "rgba(176, 184, 193, 0.22)",
                    "accentSoft": "rgba(201, 151, 82, 0.16)",
                    "gridLine": "rgba(107, 116, 128, 0.08)",
                },
                fonts={
                    "title": APTOS_TITLE_FONT,
                    "body": APTOS_BODY_FONT,
                },
                borderRadius={
                    "xl": "24px",
                    "lg": "18px",
                    "md": "12px",
                },
                shadows={
                    "default": "0 26px 54px rgba(85, 92, 101, 0.14)",
                    "soft": "0 12px 28px rgba(85, 92, 101, 0.1)",
                    "card": "0 16px 34px rgba(85, 92, 101, 0.12)",
                },
                animationStyle="minimal",
            ),
            ThemeConfig(
                id="tech-dark",
                label="科技暗色",
                description="科技感暗色主题，作为可选项提供，不作为默认主题。",
                appearance="dark",
                colors={
                    "primary": "#57c7ff",
                    "secondary": "#7f92ff",
                    "accent": "#f7b955",
                    "background": "#0f1724",
                    "surface": "#182334",
                    "surfaceStrong": "rgba(23, 34, 51, 0.96)",
                    "surfaceSoft": "rgba(34, 48, 69, 0.78)",
                    "text": "#edf3ff",
                    "textSecondary": "#a7b4cb",
                    "border": "#304259",
                    "danger": "#ff7a68",
                    "dangerSoft": "rgba(255, 122, 104, 0.18)",
                    "neutralSoft": "rgba(167, 180, 203, 0.14)",
                    "primarySoft": "rgba(87, 199, 255, 0.18)",
                    "secondarySoft": "rgba(127, 146, 255, 0.22)",
                    "accentSoft": "rgba(247, 185, 85, 0.18)",
                    "gridLine": "rgba(127, 146, 255, 0.12)",
                },
                fonts={
                    "title": APTOS_TITLE_FONT,
                    "body": APTOS_BODY_FONT,
                },
                borderRadius={
                    "xl": "26px",
                    "lg": "20px",
                    "md": "14px",
                },
                shadows={
                    "default": "0 28px 60px rgba(3, 10, 20, 0.42)",
                    "soft": "0 14px 32px rgba(3, 10, 20, 0.34)",
                    "card": "0 18px 40px rgba(3, 10, 20, 0.36)",
                },
                animationStyle="dynamic",
            ),
        )
